### ISSUE TITLE
Regarding W^ matrices dimensionality.

### ISSUE THREAD

**Issue by TangZJ** [chenfengxu714/YOGO#1]
Hi, in your paper, the W^q, v, k matrices are 256 by 256 (Ct by Ct). 
However, in your code for s3dis yoga, the W^k,q matrices are 256 by 128.

Could you clarify on the dimensionality of the W^ matrices

  (stage1): Sequential(
    (0): RIM_ResidualBlock(
      (res_connect): Sequential(
        (0): Conv1d(32, 64, kernel_size=(1,), stride=(1,))
        (1): InstanceNorm1d(64, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
      )
      (vt1): RIM(
        (transformer): Transformer(
          (k_conv): ModuleList(
            (0): Sequential(
              (0): Conv1d(256, 128, kernel_size=(1,), stride=(1,), bias=False)
              (1): InstanceNorm1d(128, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            )
          )
          (q_conv): ModuleList(
            (0): Sequential(
              (0): Conv1d(256, 128, kernel_size=(1,), stride=(1,), bias=False)
              (1): InstanceNorm1d(128, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            )
          )
          (v_conv): ModuleList(
            (0): Sequential(
              (0): Conv1d(256, 256, kernel_size=(1,), stride=(1,), bias=False)
              (1): InstanceNorm1d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            )
          )
          (kqv_bn): ModuleList(
            (0): InstanceNorm1d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
          )
          (kq_matmul): ModuleList(
            (0): MatMul()
          )
          (kqv_matmul): ModuleList(
            (0): MatMul()
          )
          (ff_conv): ModuleList(
            (0): Sequential(
              (0): Conv1d(256, 512, kernel_size=(1,), stride=(1,), bias=False)
              (1): InstanceNorm1d(512, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
              (2): ReLU(inplace=True)
              (3): Conv1d(512, 256, kernel_size=(1,), stride=(1,), bias=False)
              (4): InstanceNorm1d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=False)
            )
          )
        )

**Comment by chenfengxu714** [comment]
Thanks for your pinpoint. We shrink half of the output channel size of key and query to reduce the computation cost. This is a common trick in Transformer-based method, and we should detail this in our paper. We will definitely put this trick in our next version. As for the result, we find it is very slightly harmful to the performance, yet obviously improve the efficiency.
